### ISSUE TITLE
undefined sort.Slice (no previous experience with Go language)

### ISSUE THREAD

**Issue by plumdeq** [linmounong/deepwalker#1]
Hi,

I wanted to quickly try and play with your code and got the following error

```bash
go get github.com/linmounong/deepwalker
# github.com/linmounong/deepwalker
src/github.com/linmounong/deepwalker/main.go:36: undefined: sort.Slice
```

I have no prior experience with Go programming language. I'm using Ubuntu 16.04, I installed Go with `apt-get install golan`, the `GOPATH` was set to the current directory for this quick test.

**Comment by linmounong** [comment]
Hi,

I think sort.Slice was introduced in a newer version of Go. Try install go
from golang.org and build again.

Regards,
Yinong Lin

**Comment by plumdeq** [comment]
Thank you for your reply. I confirm that it works with Go v1.9.2.
